config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'public_recipes#index'

  get 'general_shopping_list', to: 'shopping_list#index', as: 'general_shopping_list'

  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes, only: [:index, :new, :create, :destroy, :show, :update] do
      resources :recipe_foods, only: [ :new, :create, :destroy]
  end
  get 'public_recipes', to: 'public_recipes#index', as: 'public_recipes'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all

    can :manage, User, id: user.id
    can :manage, Food, user_id: user.id
    can :manage, Recipe, user_id: user.id

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :user_id, presence: true
  validates :quantity, presence: true
  validates :price, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'recipe_id', dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :description, presence: true
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, class_name: 'Food', foreign_key: :food_id
  belongs_to :recipe, class_name: 'Recipe', foreign_key: :recipe_id

  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :food_id, presence: true
  validates :recipe_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true, length: { maximum: 250 }
  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.where(user_id: current_user.id)
  end

  def new
    @food = Food.new
  end

  def show; end

  def create
    @food = current_user.foods.build(food_params)

    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      flash.now[:alert] = 'Failed to create a food item. Please check the form for errors.'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      redirect_to foods_path, notice: 'Food was successfully deleted.'
    else
      redirect_to foods_path, alert: 'Failed to delete the food item.'
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :quantity, :price)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.includes(:user, recipe_foods: :food).where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.where(user_id: current_user.id)
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.build(recipe_food_params)

    if @recipe_food.save
      redirect_to recipe_path(@recipe.id), notice: 'Food added from the recipe successfully.'
    else
      @foods = Food.all
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.destroy
      redirect_to recipe_path(@recipe.id), notice: 'Food removed form the recipe successfully.'
    else
      flash.now[:alert] = 'Failed to remove food from recipe foods list.'
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def show
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @user = current_user
  end

  def create
    @user = current_user
    @recipe = @user.recipes.build(new_recipe_params)

    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe successfully created'
    else
      flash.now[:error] = @recipe.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(updated_recipe_params)
      redirect_to recipe_path(@recipe), notice: 'Recipe public status updated successfuly'
    else
      redirect_to recipe_path(@recipe), notice: 'Recipe could not be upddated'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe successfully created'
    else
      flash.now[:error] = "Couldn't delete the recipe"
    end
  end

  private

  def new_recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end

  def updated_recipe_params
    params.require(:recipe).permit(:public)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    foods = Food.includes(:recipe_foods).where({ user_id: current_user.id })
    @shopping_list = []
    @total_price = 0
    foods.each do |food|
      shopping_list_item = {
        food: food.name,
        quantity: calculate_missing_food(food),
        unit: food.measurement_unit,
        unit_price: food.price
      }
      @total_price += shopping_list_item[:quantity] * shopping_list_item[:unit_price]
      @shopping_list << shopping_list_item if (shopping_list_item[:quantity]).positive?
    end
  end

  private

  def calculate_missing_food(food)
    missing_food = -food.quantity
    food.recipe_foods.each do |recipe_food|
      missing_food += recipe_food.quantity
    end

    return 0 if missing_food <= 0

    missing_food
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/views/foods/index.html.erb
<div class="container mt-4">
<div class="container d-flex justify-content-end mr-2">
    <%= link_to 'Add new food', new_food_path, class:"btn btn-success m-4"%>
</div>

<table class="table table-striped m-3 table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Unit</th>
            <th col-span>Action</th>
        </tr>
    </thead>
    <tbody>
        <% @foods.each_with_index do |food, index| %>
        <tr>
            <td> <%= food.name %> </td>
            <td> <%= food.quantity %> </td>
            <td> <%= food.price %> $</td>
            <td> <%= food.measurement_unit %> </td>
            <td>
                   <%= link_to "Delete", food_path(food), method: :delete, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }, class: 'btn btn-outline-danger' %>
            </td>
        </tr>
        <%end%>
    </tbody>
</table>

</div>

app/views/foods/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title text-center">Create Food</h2>
          
          <%= form_with model: @food, url: foods_path, method: :post, local: true, html: { class: 'form' } do |form| %>
            <div class="form-group">
              <%= form.label :name %>
              <%= form.text_field :name, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= form.label :measurement_unit %>
              <%= form.text_field :measurement_unit, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= form.label :quantity %>
              <%= form.number_field :quantity, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= form.label :price %>
              <%= form.number_field :price, class: 'form-control' %>
            </div>

            <div class="form-group text-center">
              <%= form.submit 'Create Food', class: 'btn btn-primary btn-block mt-2' %>
            </div>
          <% end %>
          <%= link_to 'Cancel', foods_path, class:"btn btn-info"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <%= link_to 'Recipe App', root_path, class:"navbar-brand text-info"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
      <% if user_signed_in? %>
        <%= link_to 'Foods', foods_path, class:"nav-link text-light"%>
        <%= link_to 'Recipe', recipes_path, class: "nav-link text-light" %>
        <%= link_to 'Shopping list', general_shopping_list_path, class: "nav-link text-light" %>
        <%= link_to 'Sing out', destroy_user_session_path, data: { turbo_method: :delete }, class:"nav-link text-warning ms-5 ps-5"%>
        <% else %>
        <%= link_to 'Sign In', new_user_session_path, class:"nav-link text-light"%>
        <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link text-light"%>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header'%>
  <div class='container justify-content-center text-center'>
      <% flash.each do |type, message| %>
    <div class="alert alert-<%= type %>">
      <%= message %>
    </div>
  <% end %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="row justify-content-center mt-5">
  <div class="col-md-8">
    <% @public_recipes.each do |recipe| %>
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><%= link_to recipe.name, recipe_path(recipe.id) %></h5>
              <h4>By  <%= recipe.user.name %></h4>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card-body">
              <p class="card-text">Total food: <%= recipe.recipe_foods.sum(:quantity) %></p>
              <p class="card-text">Total price: $<%= recipe.recipe_foods.sum { |rf| rf.quantity * rf.food.price } %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%= link_to 'Add a recipe', new_recipe_path, class: "btn btn-success" %>
  </div>
</div>

app/views/recipe_foods/new.html.erb
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">Add Food to Recipe</h2>

          <%= form_with model: [@recipe, @recipe_food], url: recipe_recipe_foods_path(@recipe), method: :post, html: { class: 'form' } do |form| %>
            <div class="form-group">
              <%= form.label :food_id, 'Food' %>
              <%= form.collection_select :food_id, @foods, :id, :name, { prompt: 'Select a food' }, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= form.label :quantity, 'Quantity' %>
              <%= form.number_field :quantity, placeholder: 'Enter quantity', class: 'form-control' %>
            </div>

            <div class="form-group text-center">
              <%= form.submit 'Add Food', class: 'btn btn-primary btn-block' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/recipes/_recipe_food_row.html.erb
<tr>
    <td><%= recipe_food.food.name %></td>
    <td><%= recipe_food.quantity %></td>
    <td><%= recipe_food.food.price %>$</td>
    <td>
        <%=  link_to "REMOVE", recipe_recipe_food_path(recipe.id, recipe_food.id), data: { "turbo-method": :delete }, class:"btn btn-outline-danger" %>
    </td>
</tr>

app/views/recipes/index.html.erb
<div class="row justify-content-center mt-5">
  <div class="col-md-8">
    <% @recipes.each do |recipe| %>
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><%= link_to recipe.name, recipe_path(recipe.id) %></h5>
              <button class="btn btn-danger float-start" data-turbo-frame="_top">Remove</button>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card-body">
              <p class="card-text"><%= recipe.description %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%= link_to 'Add a recipe', new_recipe_path, class: "btn btn-success" %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title text-center">Create Recipe</h2>
          <%= form_with model: @recipe, url: recipes_path, method: :post, html: { class: 'form' } do |f| %>
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :preparation_time %>
              <%= f.number_field :preparation_time, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :cooking_time %>
              <%= f.number_field :cooking_time, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :public %>
              <%= f.select :public, [['Public', true], ['Private', false]], class: 'form-control' %>
            </div>

            <%= f.hidden_field :user_id, value: @user.id %>

            <div class="form-group text-center">
              <%= f.submit "Create Recipe", class: 'btn btn-primary btn-block' %>
            </div>
          <% end %>
          <%= link_to 'Cancel', recipes_path, class:"btn btn-info"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="row justify-content-center mt-4">
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <div class="container d-flex justify-content-center align-items-center">
          <h2 class="card-title"><%= @recipe.name %></h2>
        </div>

        <div class="container d-flex justify-content-between">
          <div>
            <p>Preparation Time: <%= @recipe.preparation_time %></p>
            <p>Cooking Time: <%= @recipe.cooking_time %></p>
            <p>Description: <%= @recipe.description %></p>
          </div>
          <div>
            <% if can? :update, @recipe %>
              <%= form_with url: recipe_path(@recipe), data: { "turbo-method": :patch }, model: @recipe do |form| %>
                  <%= form.label :public, 'Public' %>
                  <%= form.check_box :public, id: "public-checkbox", onchange: "this.form.submit();" %>
                </div>
              <% end %>          
            <% end %>
          </div>
        </div>
        <div class="container d-flex justify-content-between">
          <%= link_to 'generate shopping list', shopping_list_path %>
          <div>
            <% if can? :update, @recipe %>
              <%= link_to 'Add Ingredients', new_recipe_recipe_food_path(@recipe.id), class: 'btn btn-primary mb-2' %>
            <% end %>
          </div>
        </div>
        <table class="table table-bordered">
          <thead class="thead-dark">
            <tr>
              <th>Food</th>
              <th>Quantity</th>
              <th>Value</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @recipe.recipe_foods.each do |recipe_food| %>
              <%= render partial: 'recipe_food_row', locals: { recipe_food: recipe_food, recipe: @recipe } %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/shopping_list/index.html.erb
<div class="row justify-content-center mt-4">
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <div class="container d-flex justify-content-center">
                    <h1>Shopping list</h1>
                </div>
                    <div class="container d-flex justify-content-between">
                        <p>Amount of food to buy: <span><%= @shopping_list.length %></span></p>
                        <p>Total value of food needed: <%= @total_price %></span> $</p>
                    </div>
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Food</th>
                                <th>Quantity</th>
                                <th>Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @shopping_list.each do |shopping_list_item| %>
                                <tr>
                                    <td><%= shopping_list_item[:food] %></td>
                                    <td><%= "#{shopping_list_item[:quantity]} #{shopping_list_item[:unit]}" %></td>
                                    <td><%= "#{shopping_list_item[:unit_price] * shopping_list_item[:quantity]} $" %></td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>>
</div>

app/views/users/index.html.erb
<h1>Users page</h1>